Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui',
]

if env['QT_MAJOR_VERSION'] > 4:
    modules += [
        'Widgets',
    ]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')
env.Uic4(Glob('*.ui'))

env.AppendUnique(LIBPATH = [
    '../uibase',
])

env.AppendUnique(LIBS = [
    'uibase',
    'shell32',
])

# Note the order of this is important, or you can pick up the wrong report.h...
# Doing appendunique seems to throw the moc code into a tizzy
env['CPPPATH'] += [
    '../uibase',
    '.',            # Why is this necessary?
    '${BOOSTPATH}',
]

env.AppendUnique(LINKFLAGS = [
    '/SUBSYSTEM:WINDOWS',
    '${EXE_MANIFEST_DEPENDENCY}'
])

# This extra cpp is just sad. It probably means something is set up wrong.
prog = env.Program('nxmhandler',
               env.Glob('*.cpp') + env.Object('json.obj', '../uibase/json.cpp'))

env.InstallModule(prog)

#release:QMAKE_CXXFLAGS += /Zi /GL
#release:QMAKE_LFLAGS += /DEBUG /LTCG /OPT:REF /OPT:ICF
